### ISSUE TITLE
Output TSV should provide file path

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/spellcheck#17]
From https://github.com/AlexsLemonade/OpenScPCA-analysis/pull/485#issue-2331693006:

> One other comment I have is that the results tsv file tells you the filename, but not the relative path to the file within the module (or even what module it is). I feel like that might be something we want to do otherwise these spell checks could get out of hand.

We should update the TSV output here to print the file path, not just the file name.

**Comment by sjspielman** [comment]
It unfortunately looks like the `spelling` package can only return the file names, and not their path. Implementing this will therefore require (probably?) breaking up the `files` vector before heading into `spelling::spell_check_files()` and checking sets of paths one at a time, and then combining results.

**Comment by jashapiro** [comment]
It may be easier to do it a directory at a time? Get the list of files, then use `dirname() |> unique()` to get the list of directories to check, then you can just prepend that onto the file names. But maybe that is no more efficient

**Comment by sjspielman** [comment]
Noting that we can also bump to version `0.3` when this goes in.

**Comment by sjspielman** [comment]
`v0.3.0` is released and `v0` has been bumped up to match.
